- hosts: all
  become: yes
  user: root
  vars:
    - mysql_root_password: password
    - mysql_user_name: vagrant
    - mysql_user_password: vagrant

  tasks:
    - name: set timezone to Asia/Tokyo
      timezone:
        name: Asia/Tokyo

    - name: install epel
      yum:
        name: epel-release
        state: present

    - name: install remi repository
      yum:
        name: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
        state: present

    - name: install net-tools
      yum:
        name: net-tools
        state: present

    - name: install httpd
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - httpd
        - mod_ssl
        - mod_geoip

    - name: install php
      yum:
        name: "{{ item }}"
        state: present
        enablerepo: remi,remi-php72
      with_items:
        - php
        - php-devel
        - php-mbstring
        - php-pdo
        - php-xml
        - php-tokenizer
        - php-json
        - php-ctype
        - php-openssl
        - php-mysql

    - name: install composer
      shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin && mv /usr/bin/composer.phar /usr/bin/composer
         creates=/usr/bin/composer

    - name: uninstall mariaDB
      yum:
        name: mariadb-libs
        state: absent

    - name: uninstall default mysql
      yum:
        name: mysql*
        state: absent

    - name: remove mariaDB date
      shell: rm -rf /var/lib/mysql

    - name: install rpm repository
      yum: 
        name: https://dev.mysql.com/get/mysql57-community-release-el6-11.noarch.rpm
        state: present

    - name: install mysql
      yum:
        name: "{{ item }}"
        enablerepo: mysql56-community
        disablerepo: mysql57-community
        state: present
      with_items:
        - mysql-community-server
        - mysql-community-client
        - mysql-community-common
        - mysql-community-libs
        - mysql-community-libs-compat
        - MySQL-python
        - libselinux-python

    - name: mysqld systemctl setting
      service:
        name: mysqld
        state: started
        enabled: yes

    - name: change root password
      mysql_user:
        name: root
        password: "{{ mysql_root_password }}"
        host: "{{ item }}"
      with_items:
        - 127.0.0.1
        - ::1
        - localhost.localdomain
        - localhost

    - name: /root/.my.cnf by template
      template: 
        src: my.cnf.j2
        dest: /root/.my.cnf
        owner: root
        group: root
        mode: 0600

    - name: add user
      mysql_user:
        name: "{{mysql_user_name}}"
        password: "{{mysql_user_password}}"
        host: localhost
        priv: '*.*:ALL,GRANT'

    - name: restart network
      service:
        name: network
        state: restarted
        enabled: yes

    - name: start httpd
      service:
        name: httpd
        state: started
        enabled: yes
