# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "CentOS72"

  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false

    # Customize the amount of memory on the VM:
    vb.memory = "512"
  end

  config.vm.provision "ansible_local" do |ansible|
    ansible.install = true
    ansible.playbook = "playbook.yml"
  end

  config.vm.synced_folder "../web", "/app/fighter-curation", create: "true", :mount_options => ['dmode=777', 'fmode=777']

  config.vm.provision :shell, run: "always", :inline => <<-EOT
    sudo systemctl start httpd
  EOT
end
